name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE: ${{ steps.build-image.outputs.IMAGE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t connector-core -f docker/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        id: build-image
        run: |
          docker tag connector-core ${{ secrets.DOCKER_USERNAME }}/$IMAGE
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
        env:
          IMAGE: connector-core:${{ github.run_id }}

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop existing container on AWS Lightsail
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          docker stop connector-app connector-scheduler || true
          docker rm connector-app connector-scheduler || true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy App to AWS Lightsail
        env:
          IMAGE: ${{ needs.build.outputs.IMAGE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          # Run the Docker container on AWS Lightsail
          docker run -d --name=connector-app --network=backend \
          -e DATABASE_URL=$DATABASE_URL \
          -e S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID \
          -e S3_BUCKET_NAME=$S3_BUCKET_NAME \
          -e S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY \
          -e AWS_REGION=$AWS_REGION \
          -e SECRET_KEY=$SECRET_KEY \
          --memory=96m \
          ${{ secrets.DOCKER_USERNAME }}/$IMAGE \
          sh -c "aerich upgrade && uvicorn code.app:app --host 0.0.0.0 --port 8000"

      - name: Deploy Scheduler to AWS Lightsail
        env:
          IMAGE: ${{ needs.build.outputs.IMAGE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          # Run the Docker container on AWS Lightsail
          docker run -d --name=connector-scheduler \
          -e DATABASE_URL=$DATABASE_URL \
          -e S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID \
          -e S3_BUCKET_NAME=$S3_BUCKET_NAME \
          -e S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY \
          -e AWS_REGION=$AWS_REGION \
          -e SECRET_KEY=$SECRET_KEY \
          --memory=64m \
          ${{ secrets.DOCKER_USERNAME }}/$IMAGE \
          sh -c "aerich upgrade && python -m code.scheduler"
